# Copyright (c) 2024, NVIDIA CORPORATION.

{% set pyproject_data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="VERSION",
    regex_pattern="(?P<value>[0-9]+[0-9a-z\-.]+)"
)[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set project_data = pyproject_data["project"] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}

# build 2 variants, with corresponding build strings:
#
#  '*_cpu' for CPU-only
#  '*_gpu' for systems with CUDA
#
# this mirrors the approach used by cunumeric / legate-core
# (though as of 24.06, they do not append a '*_gpu' to the build string for GPU packages)
{% if gpu_enabled == "true" %}
  {% set gpu_enabled_bool = true %}
{% elif gpu_enabled == "false" %}
  {% set gpu_enabled_bool = false %}
{% else %}
  {% set gpu_enabled_bool = true %}
{% endif %}

{% if gpu_enabled_bool %}
  {% set processor_tag='_gpu' %}
{% else %}
  {% set processor_tag='_cpu' %}
{% endif %}

package:
  name: legate-boost
  version: {{ version }}

source:
  path: ../../..

build:
  string: "cuda{{ cuda_major }}_py{{ py_version }}_{{ PKG_BUILDNUM }}{{ processor_tag }}"
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - CONDA_OVERRIDE_CUDA
    - CUDAARCHS
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=legate-boost-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=legate-boost-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS
  ignore_run_exports_from:
    {% if gpu_enabled_bool %}
    - {{ compiler('cuda') }}
    {% endif %}
  {% if not gpu_enabled_bool %}
  # The CPU-only packages having more track_features than the GPU builds helps
  # the solver to prefer the GPU builds when both are viable candidates.
  # ref: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#track-features
  track_features:
    - cpu_only
  {% endif %}

requirements:
  build:
    - cmake {{ cmake_version }}
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cuda-nvcc
    - {{ stdlib("c") }}
  host:
    {% if gpu_enabled_bool %}
    - cuda-version ={{ cuda_version }}
    - cuda-cudart-dev
    - cunumeric {{ legate_version }}
    - legate-core {{ legate_version }}
    - libcublas-dev
    {% else %}
    - cunumeric {{ legate_version }} =*_cpu
    - legate-core {{ legate_version }} =*_cpu
    {% endif %}
    - openblas
    - python
    - pip
    - scikit-build >=0.18.0
    - setuptools >=70.0
    # try to expose what's pulling in 'mkl'
    - nomkl
  run:
    - python
    {% if gpu_enabled_bool %}
    # cuda-version is used to constrain __cuda
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    - __cuda
    - cunumeric {{ legate_version }}
    {% else %}
    - cunumeric {{ legate_version }} =*_cpu
    {% endif %}
    # Relying on run_exports from legate-core to pin an appropriate range of versions and
    # GPU vs. CPU selector.
    #
    # legate-core uses {{ pin_subpackage(name, min_pin="x.x.x", max_pin="x.x.x") }}, which means
    # that if legate-boost builds against, say, legate-core=24.06.0 and then a legate-core=24.06.1 is
    # released, a new legate-boost would be required.
    - legate-core
    - numpy
    - scikit-learn
    - typing-extensions>=4.0
    - nomkl

test:
  # import tests at build time do not work for the CUDA packages,
  # because builds happen on machines without a GPU
  {% if not gpu_enabled_bool %}
  imports:
    - legateboost
    - legateboost.metrics
    - legateboost.models
    - legateboost.objectives
  {% endif %}
  commands:
    - pip show legate-boost

about:
  license: {{ project_data["license"]["text"] }}
  license_family: Apache
  license_file: LICENSE
  summary: {{ project_data["description"] }}
