#!/bin/bash

# A utility script that generates a package version
#
#
# Adopted from `rapids-generate-version` and `rapids-is-release-build`
# (https://github.com/rapidsai/gha-tools/blob/c5a6fef8b6455d524aefe3baf2432a68872e5b8f/tools/rapids-generate-version),
# with minor changes to account for differences between how Legate and RAPIDS packages are versioned.

set -euo pipefail
base_version=$(head -1 ./VERSION)

# If the build was triggered by a new tag being pushed to the repo, the package version
# should just be the version in the VERSION file.
if [[ "${GITHUB_REF:-}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo -n "${base_version}"
else
    # otherwise, the version should be that tag + an integer with the number of commits since that tag,
    dunamai_version=$(python -m dunamai from git --format "${base_version}dev{distance}")
    echo -n "${dunamai_version}"
fi
