name: pr

concurrency:
  group: ci-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  # run on pushes to certain branches
  push:
    branches:
      - "pull-request/[0-9]+"

env:
  # CUDA architectures to build for
  CUDAARCHS: "all-major"
  # where jobs that download conda packages store the local channel
  RAPIDS_LOCAL_CONDA_CHANNEL: /tmp/local-conda-packages

jobs:

  check-settings:
    runs-on: ubuntu-latest
    steps:
      - name: do-stuff
        run: |
          echo "inputs.deploy_docs: ${{ inputs.deploy_docs }}"
          echo "inputs.deploy_docs == true: ${{ inputs.deploy_docs == true }}"
          echo "github.event_name: ${{ github.event_name }}"
  docs-build:
    needs:
      - check-settings
    uses: ./.github/workflows/docs-build.yaml
    with:
      script: "ci/build_docs.sh"
      deploy: ${{ github.event_name == 'tag' || inputs.deploy_docs == true }}
    secrets: inherit
