name: Project - Set Sprint

on:
  pull_request_target:
    # We will ensure the sprint is the current sprint when an issue is (re)opened, synchronized, or edited
    types: [opened, synchronize, reopened, edited]

jobs:
  call-reusable-job:
    permissions:
        contents: read
    uses: rapidsai/gpu-xb-ai/.github/workflows/reusable-project-set-sprint.yml@main
    secrets: inherit
